title = "Bezier"
gitRepoUrl = "https://github.com/bstummer/bezier"

gitSourceBranch = "main"
changelog = true
classOrder = []

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"

organizationName = "bstummer"
projectName = "Bezier"
url = "https://bstummer.github.io"
baseUrl = "/bezier/"
tagline = "Advanced Bézier curves module"

[[navbar.items]]
href = "https://devforum.roblox.com/t/2043623"
label = "Forum post"
position = "right"

[footer]
style = "dark"
copyright = " "

[[footer.links]]
title = "Links"

[[footer.links.items]]
label = "Introduction"
href = "https://bstummer.github.io/bezier/docs/intro"

[[footer.links.items]]
label = "API"
href = "https://bstummer.github.io/bezier/api/Bezier"